name: Lint

on:
  - pull_request

jobs:
  phpcbf:
    name: phpcbf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Get composer cache dir
        run: printf "dir=%s\n" "$(composer config cache-files-dir)" >>"$GITHUB_OUTPUT"
        id: get-composer-cache-dir
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          # https://github.com/actions/cache/blob/main/examples.md#php---composer
          path: ${{ steps.get-composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - run: composer --ansi install
      - name: Run phpcbf
        run: |
          set -x +e
          rc=0
          vendor/bin/phpcbf --runtime-set php_version 70200 --runtime-set ignore_non_auto_fixable_on_exit 1 --colors .; ((rc+=$?))
          git diff --color --exit-code; ((rc+=$?))
          ((rc==0))
